# config/paths.yml

path_to_laz: data/raw/laz
path_to_sat: data/raw/sat

path_to_dtm: data/processed/dtm
path_to_vis: data/processed/vis

path_to_metadata: data/metadata
path_to_examples: data/example

path_to_pdal_templates: config/pdal_pipeline_templates
